### PR TITLE
Add a "help wanted" section

### PR DESCRIPTION
**Pull request by cybette**
@samccann @GregSutcliffe what do you think`?

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
LGTM
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by samccann** [comment]
LGTM but how does a person specify their newsbot item is for one of these sections?

**Comment by GregSutcliffe** [comment]
Via reactions - that's what the :pray: is for. Only editors have the official right to apply a section/project, but users can make it easier if they apply the appropriate section themselves - not required though.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cybette** [comment]
@samccann what greg said (he types faster from his android device than I from my laptop :stuck_out_tongue:) If you have some help wanted items please share via newsbot and we can try the new section emoji as an example :)

**Pull request merged**
